-- @author Ed Kashinsky
-- @description ek_Pitch Tool
-- @version 1.0.0
-- @metapackage
-- @about
--    Pitch tool brings Ableton workflow for pitch manipulations of audio clips.
--       - Change pitch mode for selected items menu
--       - Toggle preserve pitch for selected items
--       - Increase/Decrease pitch or rate for selected items
--       - Switch to prev/next pitch mode for selected items
--       - Clear pitch or rate for selected items
-- @provides
--   [main=main] ek_Pitch Tool - Change pitch mode for selected items menu.lua
--   [main=main] ek_Pitch Tool - Clear pitch or rate for selected items.lua
--   [main=main] ek_Pitch Tool - Decrease pitch or rate for selected items.lua
--   [main=main] ek_Pitch Tool - Increase pitch or rate for selected items.lua
--   [main=main] ek_Pitch Tool - Switch to next pitch mode for selected items.lua
--   [main=main] ek_Pitch Tool - Switch to prev pitch mode for selected items.lua
--   [main=main] ek_Pitch Tool - Toggle preserve pitch for selected items.lua