-- @description ek_Tracks collapser
-- @version 1.0.0
-- @author Ed Kashinsky
-- @about
--   This package has 2 scripts "ek_Collapse selected tracks" and "ek_Expand selected tracks". They toggle selected tracks/envelope lanes between 3 states: small, medium, large.
--   Execute one of these scripts on transport panel and put height values there
-- @metapackage
-- @provides
--   ../Core/ek_Tracks collapser functions.lua
--   [main=main] ek_Collapse selected tracks.lua
--   [main=main] ek_Expand selected tracks.lua